version: '3.7'
services:
  db:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
    - ./.data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: curso-pgadmin
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PGADMIN_PASSWORD}
    ports:
      - "8000:80"
    depends_on:
      - db