version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
    - ./.data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
